<?php

namespace AppBundle\Repository;

/**
 * DaneSuszeniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaneSuszeniaRepository extends \Doctrine\ORM\EntityRepository
{
    
}
